name: DIP
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8  # 由于M1 Mac对Python 3.6支持有限，升级到3.8
  - pytorch
  - torchvision
  - jupyter
  - nb_conda
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - pip
  - setuptools
  - cmake
  - cffi
